version: '3.5'
services:
  flyway-pg:
    container_name: flyway-pg
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./entrypoint-scripts:/docker-entrypoint-initdb.d/
      - type: volume
        source: flyway-pg-data
        target: /var/lib/postgresql/data
    networks:
      - default
  flyway-pgadmin:
    container_name: flyway-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@example.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "8080:80"
    networks:
      - default
volumes:
  flyway-pg-data:
    name: flyway-pg-data
networks:
  default:
    name: flywaynet
    driver: bridge